apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns-role
  namespace: {{ .Release.Name }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
      - configmaps
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
      - project.openshift.io
    resources:
      - projects
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces