apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns-role
  namespace: {{ .Release.Name }}
rules:
  - verbs:
      - create
      - get
      - update
    apiGroups:
      - submariner.io
    resources:
      - brokers