{{- $ns := .Files.Get "templates/namespace.yaml" | fromYaml }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns-role
  namespace: {{ $ns.metadata.name }}
rules:
  - verbs:
      - create
      - get
      - update
    apiGroups:
      - submariner.io
    resources:
      - brokers