apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}
spec:
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.13-x86_64
  pullSecret:
    name: pullsecret-cluster
  sshKey:
    name: sshkey-cluster
  networking:
    clusterNetwork:
      - cidr: 10.132.0.0/14
    serviceNetwork:
      - cidr: 172.31.0.0/16
    networkType: OVNKubernetes
  platform:
    type: KubeVirt
    kubevirt:
      baseDomainPassthrough: true
      credentials:
        infraNamespace: scaletest
        infraKubeConfigSecret:
          key: kubeconfig
          name: external-kubeconfig
  infraID: {{ .Release.Namespace }}-{{ .Release.Name }}
  dns:
    baseDomain: ''
  services:
  - service: APIServer
    servicePublishingStrategy:
      type: LoadBalancer
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: OIDC
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route
